{
//=========Macro generated from canvas: Test canvas/Test canvas
//=========  (Fri Jun 10 11:50:17 2011) by ROOT version5.18/00
   TCanvas *Test canvas = new TCanvas("Test canvas", "Test canvas",73,22,1015,602);
   gStyle->SetOptStat(0);
   Test canvas->Range(-0.9710494,46.00213,5.126659,76.49254);
   Test canvas->SetFillColor(0);
   Test canvas->SetBorderMode(0);
   Test canvas->SetBorderSize(2);
   Test canvas->SetTickx();
   Test canvas->SetTicky();
   Test canvas->SetLeftMargin(0.1592483);
   Test canvas->SetRightMargin(0.02077151);
   Test canvas->SetTopMargin(0.04895105);
   Test canvas->SetBottomMargin(0.1311189);
   Test canvas->SetFrameFillStyle(0);
   Test canvas->SetFrameBorderMode(0);
   Test canvas->SetFrameFillStyle(0);
   Test canvas->SetFrameBorderMode(0);
   
   TH1 *All1 = new TH1F("All1","All1",1,0,5);
   All1->SetMinimum(50);
   All1->SetMaximum(75);
   All1->SetStats(0);
   All1->SetFillStyle(0);
   All1->SetLineStyle(0);
   All1->SetMarkerStyle(20);
   All1->GetXaxis()->SetTitle("Minimum p_{t} [MeV]");
   All1->GetXaxis()->SetNdivisions(109);
   All1->GetXaxis()->SetLabelFont(42);
   All1->GetXaxis()->SetLabelOffset(0.007);
   All1->GetXaxis()->SetLabelSize(0.05);
   All1->GetXaxis()->SetTitleSize(0.06);
   All1->GetXaxis()->SetTitleOffset(0.75);
   All1->GetXaxis()->SetTitleFont(42);
   All1->GetYaxis()->SetTitle("#sigma [mb]");
   All1->GetYaxis()->SetLabelFont(42);
   All1->GetYaxis()->SetLabelOffset(0.007);
   All1->GetYaxis()->SetLabelSize(0.05);
   All1->GetYaxis()->SetTitleSize(0.06);
   All1->GetYaxis()->SetTitleOffset(0.8);
   All1->GetYaxis()->SetTitleFont(42);
   All1->GetZaxis()->SetLabelFont(42);
   All1->GetZaxis()->SetLabelOffset(0.007);
   All1->GetZaxis()->SetLabelSize(0.05);
   All1->GetZaxis()->SetTitleSize(0.06);
   All1->GetZaxis()->SetTitleFont(42);
   All1->Draw("");
   
   TGraphErrors *gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2,58.7);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3,57.2);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4,55.4);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineWidth(3);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2,58.7);
   gre->SetPointError(0,0,2.4);
   gre->SetPoint(1,3,57.2);
   gre->SetPointError(1,0,2.4);
   gre->SetPoint(2,4,55.4);
   gre->SetPointError(2,0,2.4);
   gre->Draw("pe1");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetLineWidth(3);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2,58.7);
   gre->SetPointError(0,0,2);
   gre->SetPoint(1,3,57.2);
   gre->SetPointError(1,0,2);
   gre->SetPoint(2,4,55.4);
   gre->SetPointError(2,0,2);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(3);
   gre->SetMarkerStyle(21);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,0);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,59.6);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,57.2);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(22);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,64.6);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,61.9);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,60.8);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(6);
   gre->SetMarkerStyle(23);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,0);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,71.8);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,70.5);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(7);
   gre->SetMarkerStyle(24);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,-2.000001);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,56.4);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,55.7);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(8);
   gre->SetMarkerStyle(25);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,67);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,65.2);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,64.6);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(9);
   gre->SetMarkerStyle(26);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,72.5);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,71.5);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,71);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   
   gre = new TGraphErrors(3);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(27);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,2.1,0);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,3.1,60.7);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,4.1,59);
   gre->SetPointError(2,0,0);
   gre->Draw("p");
   TLatex *   tex = new TLatex(0.11,73,"CMS Preliminary, #sqrt{s} = 7 TeV, L = 36 pb^{-1}");
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.2,0.2,0.35,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","CMS Preliminary","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","PYTHIA D6T","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(3);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","PYTHIA8","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","PHOJET","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(6);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","QGSJET-II-03","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(7);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","QGSJET-II-04","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(8);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","SIBYLL-2.1","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(9);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.7);
   entry=leg->AddEntry("Graph","EPOS","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(27);
   entry->SetMarkerSize(1.7);
   leg->Draw();
      tex = new TLatex(0.11,75.2,"Inelastic pp cross section for events with at least 3 charged particles  in |#eta| < 2.4");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   Test canvas->Modified();
   Test canvas->cd();
   Test canvas->SetSelected(Test canvas);
}
